name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Build
        run: mise run build

      - name: Test
        run: mise run test

      - name: Lint
        run: mise run lint
